apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bit
  namespace: bit
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 5m
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - bit.elroy.site
    secretName: bit-tls
  rules:
  - host: bit.elroy.site
    http:
      paths:
      - path: /cashier
        pathType: Prefix
        backend: {service: {name: cashier-ui, port: {number: 80}}}
      - path: /admin
        pathType: Prefix
        backend: {service: {name: admin-ui, port: {number: 80}}}
      - path: /api
        pathType: Prefix
        backend: {service: {name: backend, port: {number: 8000}}}
      - path: /
        pathType: Prefix
        backend: {service: {name: cashier-ui, port: {number: 80}}}
